### ISSUE TITLE
Weird issue after update from 0.1.0 to 0.1.1

### ISSUE THREAD

**Issue by doosterkamp** [bdraco/aiohttp-fast-zlib#8]
**Describe the bug**
Beginning with the `2024.7.x` version of Home Assistant (in which **_you_** bumped this library to `0.1.1`, I believe) a custom integration some of us use, stopped working:
see https://github.com/runDMCA/home-assistant-mazda/issues/5 for details on this issue.

**To Reproduce**
- Buy a Mazda and install home assistant, with the m@zda integration (or contact me to assist you somehow ;P ) 

**Additional context**
I know there hasn't been an actual change to `aiohttp-fast-zlib` in `0.1.1`, except for the license text and the version number, BUT reverting to `0.1.0` fixed the issue for me somehow. I switched a few times between `0.1.0` and `0.1.1` , with the same result everytime:
- `0.1.0`: the integration works
- `0.1.1`: the integration failes to init: 
   ```
   "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
   await self._waiter
   asyncio.exceptions.CancelledError
   ```

**Comment by bdraco** [comment]
This package can't be the source of the issue as you've already stated, there are no code changes between 0.1.0 and 0.1.1

https://github.com/bdraco/aiohttp-fast-zlib/compare/v0.1.0...v0.1.1

**Comment by guba91** [comment]
maybe one of the following?
Downgrade logging previously reported asyncio block to debug ([@bdraco](https://github.com/bdraco) - [#120942](https://github.com/home-assistant/core/pull/120942))
Add os.walk to asyncio loop blocking detection ([@bdraco](https://github.com/bdraco) - [#118769](https://github.com/home-assistant/core/pull/118769))
Ensure asyncio blocking checks are undone after tests run ([@bdraco](https://github.com/bdraco) - [#119542](https://github.com/home-assistant/core/pull/119542))

looking at the error log:
`ERROR (MainThread) [custom_components.mazda] Unknown error occurred during Mazda update request: 
                      Traceback (most recent call last):
                        File "/config/custom_components/mazda/__init__.py", line 57, in with_timeout
                          return await task
                                ^^^^^^^^^^
                        File "/config/custom_components/mazda/pymazda/client.py", line 30, in get_vehicles
                          vec_base_infos_response = await self.controller.get_vec_base_infos()
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        File "/config/custom_components/mazda/pymazda/controller.py", line 30, in get_vec_base_infos
                          return await self.connection.api_request(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        File "/config/custom_components/mazda/pymazda/connection.py", line 191, in api_request
                          return await self.__api_request_retry(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        File "/config/custom_components/mazda/pymazda/connection.py", line 221, in __api_request_retry
                          return await self.__send_api_request(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        File "/config/custom_components/mazda/pymazda/connection.py", line 329, in __send_api_request
                          response = await self._session.request(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
                          await resp.start(conn)
                        File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
                          message, payload = await protocol.read()  # type: ignore[union-attr]
                                            ^^^^^^^^^^^^^^^^^^^^^
                        File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
                          await self._waiter
                      asyncio.exceptions.CancelledError
                      The above exception was the direct cause of the following exception:
                      Traceback (most recent call last):
                        File "/config/custom_components/mazda/__init__.py", line 154, in async_update_data
                          vehicles = await with_timeout(mazda_client.get_vehicles())
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        File "/config/custom_components/mazda/__init__.py", line 56, in with_timeout
                          async with asyncio.timeout(timeout_seconds):
                        File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
                          raise TimeoutError from exc_val
                      TimeoutError`
